#!/usr/bin/env ruby

USAGE = <<EOS
Usage: git update-feature-branch <branch> [remote-branch]

<branch>        - Mandatory. This is your local branch. 
[remote-branch] - Optional.  This is the remote branch on origin. If not provided this script will use "origin/branch".
                             Next version will provide the possibility to use arbitrary remotes.

  -h, --help     shows this information
  --continue     Continues the script after interrupting due to e.g. conflict-solving. (Also next version.)

This script is idempotent. If it fails, e.g. because of conflicts, 
you can simply rerun it.

Using the cool rebasing with git, feature-branches in collaboration can get tricky if you want to keep your work up-to-date with master.
This script takes care of this.
First it rebases your local-, and the remote-branch, with master.
Second it rebases your branch with the local copy and deletes the copy.

Thank you, for using Gnyp-Soft.
EOS

# ----------------------------------------------------------------------------------
# Defining methods
# ----------------------------------------------------------------------------------


def checkout_branch(branch)
  `git checkout #{branch}`;err=$?.success?
  if !err
    puts "branch not known. aborting ..."
    exit 1
  end
end

class FileTools
  def file_name
    git_dir=`git rev-parse --show-toplevel`
    file_name= "#{git_dir.strip}/.git/.update-fb-step"
    puts file_name
    file_name
  end


  def write_step_to_file(step)
    file = File.new(file_name, "w")
    file.write(step);
  end

  def get_step_from_file
    if File.exists?(file_name)
      file = File.open(file_name) 
      file.read 
    else
      0
    end
  end
end
def exec_git(command, error_text = "Error ...", step = 0, how_to_continue_text = "")
  out=`#{command}`;!suc=$?.success?
  unless suc
    puts error_text
    if step > 0
      puts how_to_continue_text 
    end
    exit 1
  end
  out
end

# ----------------------------------------------------------------------------------

write_step_to_file 0
exit

# Checking for illegal args
if ARGV.empty? or ARGV.delete("--help") or ARGV.delete("-h")
  puts USAGE
  exit 0
end

ARGV.each { |a| abort "Error: unknown argument #{a}." if a =~ /^--/ }

branch = nil
origin_branch=nil
ARGV.each_with_index { |a, i| 
  if i == 0
    branch=a 
  end
    origin_branch="origin/#{branch}"
  if i == 1
    origin_branch="origin/#{a}"
  end
}
puts "Working with \'#{branch}\'"
puts "Remote branch \'#{origin_branch}\'"

# Testing if according branch exists and is a good one
if branch == "master"
  puts "Using master as a feature branch is not permitted!"
  exit 1
end 
checkout_branch branch

# checking for a dirty directory
puts "Checking wc clean ..."
out = `git status --porcelain` ; suc = $?.success?
if out.length > 0 
  puts "You seem to have a dirty directory. Please commit or stage your changes and start over."
  exit 1
end unless !suc

class Steps
  steps = [
    :rebase_lokal_with_master
  ]

  def run(step)
    steps.each { |e, i| 
      send steps[step] unless i < step
    }
  end

  # 1. Step - checkout master and get latest version
  def rebase_lokal_with_master(step)
    puts "sended. step: #{step}"
    exit
    puts "Pulling master and rebasing your feature-branch..."
    checkout_branch "master"
    exec_git "git fetch","Could not fetch."
    exec_git "git pull origin master", "Could not pull master", step, "Please fix problems (e.g. conflicts) with pull master.\nAfter resolving run git update-feature-branch --continue"
  end
end

steps = new Steps
steps.run(0)


checkout_branch branch
exec_git "git rebase master", "Rebasing your bransch \'#{branch}\' with master failed. Could not update your work."

# Step 2 - Updating remote feature-branch to our master 
puts "Rebasing feature-branch from origin onto local master ..."
updated_origin_branch="#{branch}_from_origin"
exec_git "git checkout #{origin_branch}","Could not checkout #{origin_branch}"
exec_git "git rebase master","Error..."
exec_git "git branch -f #{updated_origin_branch}","Could not create tempory branch #{updated_origin_branch}"
exec_git "git checkout #{updated_origin_branch}","Could not checkout tempory branch #{updated_origin_branch}"

# Step 3 - Rebasing our work to origin feature-branch
puts "Rebasing lokal feature-branch with origin ..."
checkout_branch branch
exec_git "git rebase #{updated_origin_branch}","Step 3 - Could not rebase with remote-branch."
exec_git "git branch -D #{updated_origin_branch}","Step 3 - Could not delete temporary branch #{updated_origin_branch}"

puts
puts "Successfully updated your feature-branch '#{branch}'."
exit 0

